extract_args:
  path: Datasets
  dataset: SHL-preview  #SHL-preview or SHL-complete
  signals:
  - Acc
resample_args:
  old_motion_fs: 100 #Hz
  new_motion_fs: 10
  old_location_T: 1 #s
  new_location_T: 60
  max_distance: 2 #s
  mot_sampling_method: decimate
  loc_sampling_method: nearest #nearest, linear

modify_args:
  loc_filter:
  loc_filter_window:
  loc_rescaler:
  loc_virtual_features:
  - velocity
  - acceleration
  mot_smoother:
  mot_smoother_window: 0
  mot_filter:
  mot_filter_window: 0
  mot_rescaler:
  mot_virtual_signals:
  - acc_normXYZ
  - acc_jerk
segment_args:
  loc_length: 12 # samples
  loc_stride: 1

  mot_length: 600
  mot_stride: 600

  mot_bag_size: 3
  mot_bag_step: 600

build_args:
  GPS_position: Hand
  inertial_positions:
  - Hand
  - Torso
  - Bag
  - Hips
  diff_threshold: 60 #s

  train_test_split: loso       # loso, ldo_start, ldo_end, ldo_random
  train_test_hold_out: 1

  train_val_split: lopo_stratified # lopo_stratified, ldo_start, ldo_end, ldo_random
  train_val_hold_out: 0.15

  test_bag_position: same
  test_oversampling: true
  train_bag_position: same
  train_oversampling: true
  val_bag_position: same
  val_oversampling: true

  motion_features:
  - acc_normXYZ
  - acc_jerk
  in_bags: true

  motion_form: spectrogram
  combine_sensors: concat      # concat, separate
  motion_augmentations: # ['Jittering','Permutation','TimeWarp','Rotation']
  separated_channels:
  - - Lacc_x
    - Lacc_y
    - Lacc_z
  - - Gyr_x
    - Gyr_y
    - Gyr_z
  - - Mag_x
    - Mag_y
    - Mag_z
  - - Bar
  f_interpolation: log # log, linear
  log_power: true
  spectro_window: 10 # seconds
  spectro_overlap: 9
  spectro_augmentations:
  - freq_mask
  - time_mask
  location_augmentation: true
  get_position: true

  time_features:
  - velocity
  - acceleration
  window_features:
  - Movability
  - Mean
  - Std
  batch_size: 32
  random: true

train_args:
  L: 256
  D: 256
  motion_MIL: false
  fusion: MIL

  epochs: 80
  motion_epochs: 80
  location_epochs: 200

  learning_rate: 0.0001

  motion_encoder: skip
  location_encoder: skip

  motorized: false
  exclude_modes:
  - undefined
postprocess_args:
  seq_threshold: 70 #s
