extract_args:
  path: Datasets
  dataset: SHL-preview  #SHL-preview or SHL-complete
  signals:
  - Acc
resample_args:
  old_motion_fs: 100 #Hz
  new_motion_fs: 50
  old_location_T: 1 #s
  new_location_T: 60
  max_distance: 2 #s
  mot_sampling_method: step
  loc_sampling_method: nearest #nearest, linear

modify_args:
  loc_filter:
  loc_filter_window:
  loc_rescaler:
  loc_virtual_features:
  - velocity
  - acceleration
  mot_smoother: moving_average
  mot_smoother_window: 5
  mot_filter: lowpass
  mot_filter_window: 0
  mot_rescaler: standard
  mot_virtual_signals:
  - acc_normXYZ
segment_args:
  loc_length: 12 # samples
  loc_stride: 1

  mot_length: 512
  mot_stride: 256

  mot_bag_size: 1
  mot_bag_step: 0

build_args:
  GPS_position: Hand
  inertial_positions:
  - Hand
  - Torso
  - Bag
  - Hips
  diff_threshold: 60 #s

  train_test_split: loso       # loso, ldo_start, ldo_end, ldo_random
  train_test_hold_out: 1

  train_val_split: lopo_stratified # lopo_stratified, ldo_start, ldo_end, ldo_random
  train_val_hold_out: 0.15

  test_bag_position: Torso
  test_oversampling: true
  train_bag_position: same
  train_oversampling: true
  val_bag_position: same
  val_oversampling: true

  motion_features:
  - acc_normXYZ
  in_bags: false

  motion_form: temporal
  combine_sensors: concat   # concat, separate
  motion_augmentations: # ['Jittering','Permutation','TimeWarp','Rotation']
  separated_channels:
  - - acc_jerkX
    - acc_jerkY
    - acc_jerkZ
  - - acc_normXYZ
  - - mag_jerkX
    - mag_jerkY
    - mag_jerkZ
  - - Gyr_x
    - Gyr_y
    - Gyr_z
  - - gyr_normXYZ
  f_interpolation: log # log, linear
  log_power: true
  spectro_window: 10 # seconds
  spectro_overlap: 9
  spectro_augmentations:
  - freq_mask
  - time_mask
  location_augmentation: true
  get_position: false

  time_features:
  - velocity
  - acceleration
  window_features:
  - Movability
  - Mean
  - Std
  batch_size: 100
  random: true

train_args:
  L: 256
  D: 256

  epochs: 80
  motion_epochs: 80
  location_epochs: 200

  learning_rate: 0.0001

  motion_transfer: skip
  location_transfer: skip

  motorized: false
  exclude_modes:
  - undefined
  - run
postprocess_args:
  seq_threshold: 70 #s
